"""empty message

Revision ID: 20210324_211603
Revises: 20210324_115419
Create Date: 2021-03-24 21:16:03.482561

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20210324_211603"
down_revision = "20210324_115419"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(length=255), nullable=False),
        sa.Column("is_back_test", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("market", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.Column("periods", sa.Integer(), nullable=False),
        sa.Column(
            "side", sa.Integer(), nullable=False, comment="エントリーの方向。反対売買は暗黙的にその逆とする。"
        ),
        sa.Column("size", sa.DECIMAL(), nullable=False),
        sa.Column("entry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.DECIMAL(), nullable=False),
        sa.Column(
            "entry_commission",
            sa.DECIMAL(),
            nullable=False,
            comment="手数料またはボーナス。ボーナスの場合は負数。",
        ),
        sa.Column("entry_other_commission", sa.DECIMAL(), nullable=False),
        sa.Column("entry_reason", sa.String(length=255), nullable=False),
        sa.Column("counter_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("counter_price", sa.DECIMAL(), nullable=False),
        sa.Column("counter_commission", sa.DECIMAL(), nullable=False),
        sa.Column("counter_other_commission", sa.DECIMAL(), nullable=False),
        sa.Column("counter_reason", sa.String(length=255), nullable=False),
        sa.Column(
            "interval_dt", sa.Integer(), nullable=False, comment="entryからcounterまでの日数"
        ),
        sa.Column("profit", sa.DECIMAL(), nullable=False, comment="単純な価格差による損益"),
        sa.Column("profit_rate", sa.DECIMAL(), nullable=False, comment="単純な価格差による利率"),
        sa.Column(
            "fact_profit", sa.DECIMAL(), nullable=False, comment="数量と手数料を含んだ実際の損益"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["trade_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "trade_profiles", sa.Column("name", sa.String(length=255), nullable=True)
    )
    op.add_column("trade_profiles", sa.Column("version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE trade_profiles SET name = ''")
    op.execute("UPDATE trade_profiles SET version = 1")
    op.alter_column(
        "trade_profiles", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "trade_profiles", sa.Column("version", sa.Integer(), nullable=False)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_profiles", "version")
    op.drop_column("trade_profiles", "name")
    op.drop_table("trade_logs")
    # ### end Alembic commands ###
