"""empty message

Revision ID: 20210317_000922
Revises: 20210316_070430
Create Date: 2021-03-17 00:09:22.259980

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20210317_000922"
down_revision = "20210316_070430"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etl_job_results",
        sa.Column("description", sa.String(length=1023), nullable=True),
    )
    op.execute("UPDATE etl_job_results SET description = ''")
    op.alter_column(
        "etl_job_results", "ignored", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "etl_job_results",
        sa.Column("description", sa.String(length=1023), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "etl_job_results", "ignored", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("etl_job_results", "description")
    # ### end Alembic commands ###
