"""empty message

Revision ID: 20210329_185416
Revises: 20210329_055749
Create Date: 2021-03-29 18:54:16.203463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210329_185416"
down_revision = "20210329_055749"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_profiles", sa.Column("ask_limit_rate", sa.DECIMAL(), nullable=True)
    )
    op.add_column(
        "trade_profiles", sa.Column("ask_stop_rate", sa.DECIMAL(), nullable=True)
    )
    op.add_column(
        "trade_profiles", sa.Column("bid_limit_rate", sa.DECIMAL(), nullable=True)
    )
    op.add_column(
        "trade_profiles", sa.Column("bid_stop_rate", sa.DECIMAL(), nullable=True)
    )
    op.alter_column(
        "trade_profiles", "margin", existing_type=sa.NUMERIC(), nullable=False
    )
    op.drop_column("trade_profiles", "limit_rate")
    op.drop_column("trade_profiles", "stop_rate")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_profiles",
        sa.Column("stop_rate", sa.NUMERIC(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "trade_profiles",
        sa.Column("limit_rate", sa.NUMERIC(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "trade_profiles", "margin", existing_type=sa.NUMERIC(), nullable=True
    )
    op.drop_column("trade_profiles", "bid_stop_rate")
    op.drop_column("trade_profiles", "bid_limit_rate")
    op.drop_column("trade_profiles", "ask_stop_rate")
    op.drop_column("trade_profiles", "ask_limit_rate")
    # ### end Alembic commands ###
