"""empty message

Revision ID: 20210212_002348
Revises: 20210211_223817
Create Date: 2021-02-12 00:23:48.606276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210212_002348"
down_revision = "20210211_223817"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tradeorder", sa.Column("kwargs", sa.JSON(), nullable=False))
    op.add_column(
        "tradeorder", sa.Column("order_type", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tradeorder", "order_type")
    op.drop_column("tradeorder", "kwargs")
    # ### end Alembic commands ###
