"""empty message

Revision ID: 20210326_215726
Revises: 20210326_215554
Create Date: 2021-03-26 21:57:27.097085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210326_215726'
down_revision = '20210326_215554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target')
    op.drop_table('case_node')
    op.drop_index('ix_keywords_category_name', table_name='keywords')
    op.drop_index('ix_keywords_tag', table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='keywords_pkey')
    )
    op.create_index('ix_keywords_tag', 'keywords', ['tag'], unique=False)
    op.create_index('ix_keywords_category_name', 'keywords', ['category_name'], unique=True)
    op.create_table('case_node',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('case_node_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='case_node_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('target',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['case_node.id'], name='target_node_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='target_pkey')
    )
    # ### end Alembic commands ###
