"""empty message

Revision ID: 20210316_070430
Revises: 20210315_194948
Create Date: 2021-03-16 07:04:30.366679

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20210316_070430"
down_revision = "20210315_194948"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("etl_job_results", sa.Column("ignored", sa.Integer(), nullable=True))
    op.execute("UPDATE etl_job_results SET ignored = 0")
    op.alter_column(
        "etl_job_results", sa.Column("ignored", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("etl_job_results", "ignored")
    # ### end Alembic commands ###
