"""empty message

Revision ID: 20210212_004114
Revises: 20210212_002348
Create Date: 2021-02-12 00:41:15.013631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210212_004114'
down_revision = '20210212_002348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradeorder', sa.Column('broker', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradeorder', 'broker')
    # ### end Alembic commands ###
