"""empty message

Revision ID: 20210324_115419
Revises: 20210324_003847
Create Date: 2021-03-24 11:54:19.262950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210324_115419"
down_revision = "20210324_003847"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_bots",
        sa.Column(
            "counter_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="成行前提で反対売買時に日時を確定させる。リミット・ストップの場合は、APIによって日時が取れないので認識した日付を入力。",
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "entry_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="成行前提でエントリー時に日時を確定させる",
        ),
    )
    op.alter_column(
        "trade_bots",
        "product_code",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_bots",
        "product_code",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_column("trade_bots", "entry_at")
    op.drop_column("trade_bots", "counter_at")
    # ### end Alembic commands ###
