"""empty message

Revision ID: 20210405_050907
Revises: 20210330_123734
Create Date: 2021-04-05 05:09:07.688966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210405_050907"
down_revision = "20210330_123734"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("pair", sa.String(length=255), nullable=False),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table_comment(
        "deny_tokens", "認可拒否のため、失効したアクセストークンを管理する。", existing_comment=None, schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "deny_tokens", existing_comment="認可拒否のため、失効したアクセストークンを管理する。", schema=None
    )
    op.drop_table("crypto_markets")
    # ### end Alembic commands ###
