"""empty message

Revision ID: 20210323_050840
Revises: 20210321_131305
Create Date: 2021-03-23 05:08:40.265688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20210323_050840"
down_revision = "20210321_131305"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_bots",
        sa.Column(
            "counter_order", sa.JSON(), nullable=True, comment="残エントリーを決済するための反対売買注文"
        ),
    )
    op.add_column(
        "trade_bots", sa.Column("counter_order_accepted", sa.JSON(), nullable=True)
    )
    op.add_column(
        "trade_bots", sa.Column("counter_order_finalized", sa.JSON(), nullable=True)
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "finalized", sa.JSON(), nullable=True, comment="entryとcounterの結果をまとめる"
        ),
    )
    op.alter_column(
        "trade_bots",
        "entry_cancel_order",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="リミット・ストップ監視を止めるためのキャンセル注文",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_bots",
        "entry_order",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="エントリー注文。エントリーは成行で行われ、リミット・ストップ監視まで面倒を見る。",
        existing_nullable=True,
    )
    op.drop_column("trade_bots", "close_finalized")
    op.drop_column("trade_bots", "close_order")
    op.drop_column("trade_bots", "close_cancel_order_accepted")
    op.drop_column("trade_bots", "close_order_accepted")
    op.drop_column("trade_bots", "close_order_finalized")
    op.drop_column("trade_bots", "close_cancel_order_finalized")
    op.drop_column("trade_bots", "entry_finalized")
    op.drop_column("trade_bots", "close_cancel_order")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_cancel_order",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "entry_finalized",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_cancel_order_finalized",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_order_finalized",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_order_accepted",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_cancel_order_accepted",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_order",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "trade_bots",
        sa.Column(
            "close_finalized",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "trade_bots",
        "entry_order",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="エントリー注文。エントリーは成行で行われ、リミット・ストップ監視まで面倒を見る。",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_bots",
        "entry_cancel_order",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="リミット・ストップ監視を止めるためのキャンセル注文",
        existing_nullable=True,
    )
    op.drop_column("trade_bots", "finalized")
    op.drop_column("trade_bots", "counter_order_finalized")
    op.drop_column("trade_bots", "counter_order_accepted")
    op.drop_column("trade_bots", "counter_order")
    # ### end Alembic commands ###
