"""empty message

Revision ID: 20210315_194510
Revises: 20210315_193805
Create Date: 2021-03-15 19:45:10.618097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210315_194510'
down_revision = '20210315_193805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_job_results', sa.Column('execute_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_job_results', 'execute_at')
    # ### end Alembic commands ###
