"""empty message

Revision ID: 20210330_105838
Revises: 20210330_005835
Create Date: 2021-03-30 10:58:38.542996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210330_105838'
down_revision = '20210330_005835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'trade_bots',
        'トレード戦略を実行するBOTデータを定義します。',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'trade_logs',
        'トレードの結果を格納します。',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'trade_orders',
        'アクティブ（発注済みかつ未クローズ）な注文を格納します。本テーブルデータは定期的なジョブによって、注文のクローズ確認が行われた後、TradeLog記録され、レコードは削除されます。',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'trade_profiles',
        'トレード戦略を定義する',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'trade_profiles',
        existing_comment='トレード戦略を定義する',
        schema=None
    )
    op.drop_table_comment(
        'trade_orders',
        existing_comment='アクティブ（発注済みかつ未クローズ）な注文を格納します。本テーブルデータは定期的なジョブによって、注文のクローズ確認が行われた後、TradeLog記録され、レコードは削除されます。',
        schema=None
    )
    op.drop_table_comment(
        'trade_logs',
        existing_comment='トレードの結果を格納します。',
        schema=None
    )
    op.drop_table_comment(
        'trade_bots',
        existing_comment='トレード戦略を実行するBOTデータを定義します。',
        schema=None
    )
    # ### end Alembic commands ###
