"""empty message

Revision ID: 20210326_001319
Revises: 20210325_231324
Create Date: 2021-03-26 00:13:20.106468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210326_001319"
down_revision = "20210325_231324"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "__crypto_ohlc_daily",
        sa.Column(
            "wb_cs_rate",
            sa.DECIMAL(),
            nullable=True,
            comment="white black candle stick",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("__crypto_ohlc_daily", "wb_cs_rate")
    # ### end Alembic commands ###
