"""empty message

Revision ID: 20210317_233703
Revises: 20210317_000922
Create Date: 2021-03-17 23:37:03.742561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210317_233703'
down_revision = '20210317_000922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('broker', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('analyzers', sa.JSON(), nullable=False),
    sa.Column('slippage', sa.DECIMAL(), nullable=True, comment='バックテストにおいては約定価格のブレを表現し、実際の取引ではショートサーキットのように動作します？？'),
    sa.Column('limit_rate', sa.DECIMAL(), nullable=True),
    sa.Column('stop_rate', sa.DECIMAL(), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('etl_job_results', 'description',
               existing_type=sa.VARCHAR(length=1023),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etl_job_results', 'description',
               existing_type=sa.VARCHAR(length=1023),
               nullable=True)
    op.drop_table('trade_bots')
    # ### end Alembic commands ###
