"""empty message

Revision ID: 20210315_194948
Revises: 20210315_194929
Create Date: 2021-03-15 19:49:48.502843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210315_194948"
down_revision = "20210315_194929"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_job_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execute_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=False),
        sa.Column("warning", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("etl_job_results")
    # ### end Alembic commands ###
