"""empty message

Revision ID: 20210326_235553
Revises: 20210326_215726
Create Date: 2021-03-26 23:55:53.191557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20210326_235553'
down_revision = '20210326_215726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_profile')
    op.drop_table('trade_job')
    op.drop_table('trade_detector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_detector',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1023), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('invert_ask_or_bid', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='ask bidのフラグを反転させます。'),
    sa.PrimaryKeyConstraint('id', name='trade_detector_pkey')
    )
    op.create_table('trade_job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('periods', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cron', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('broker', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bet_strategy', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_logic', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trade_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trade_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monitor_topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detector_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_check_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('order_status', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trade_job_pkey'),
    sa.UniqueConstraint('name', name='trade_job_name_key')
    )
    op.create_table('trade_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('periods', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cron', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('broker', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bet_strategy', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_logic', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trade_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trade_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monitor_topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detector_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trade_profile_pkey'),
    sa.UniqueConstraint('name', name='trade_profile_name_key')
    )
    # ### end Alembic commands ###
