"""empty message

Revision ID: 20210307_155406
Revises: 20210307_155307
Create Date: 2021-03-07 15:54:07.063760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210307_155406"
down_revision = "20210307_155307"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_account", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "trade_virtual_account", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_virtual_account", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "trade_account", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
