"""empty message

Revision ID: 20210326_215518
Revises: 20210326_194521
Create Date: 2021-03-26 21:55:18.450279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210326_215518'
down_revision = '20210326_194521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trade_order_entry_order_id_fkey', 'trade_order', type_='foreignkey')
    op.drop_constraint('trade_order_trade_virtual_account_id_fkey', 'trade_order', type_='foreignkey')
    op.drop_constraint('trade_order_trade_account_id_fkey', 'trade_order', type_='foreignkey')
    op.drop_column('trade_order', 'entry_order_id')
    op.drop_column('trade_order', 'trade_account_id')
    op.drop_column('trade_order', 'trade_virtual_account_id')
    op.drop_constraint('trade_virtual_account_latest_order_id_fkey', 'trade_virtual_account', type_='foreignkey')
    op.drop_constraint('trade_virtual_account_trade_account_id_fkey', 'trade_virtual_account', type_='foreignkey')
    op.drop_column('trade_virtual_account', 'latest_order_id')
    op.drop_column('trade_virtual_account', 'trade_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_virtual_account', sa.Column('trade_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trade_virtual_account', sa.Column('latest_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trade_virtual_account_trade_account_id_fkey', 'trade_virtual_account', 'trade_account', ['trade_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trade_virtual_account_latest_order_id_fkey', 'trade_virtual_account', 'trade_order', ['latest_order_id'], ['id'])
    op.add_column('trade_order', sa.Column('trade_virtual_account_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='アクティブな注文などがあるため、RESTRICTとする。（現在はめんどいのでCASCADE）'))
    op.add_column('trade_order', sa.Column('trade_account_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='アクティブな注文などがあるため、RESTRICTとする。（現在はめんどいのでCASCADE）'))
    op.add_column('trade_order', sa.Column('entry_order_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='エントリーとなったorder.id\u3000エントリーの時はNoneとなり、これで一連の流れを表現する'))
    op.create_foreign_key('trade_order_trade_account_id_fkey', 'trade_order', 'trade_account', ['trade_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trade_order_trade_virtual_account_id_fkey', 'trade_order', 'trade_virtual_account', ['trade_virtual_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trade_order_entry_order_id_fkey', 'trade_order', 'trade_order', ['entry_order_id'], ['id'])
    # ### end Alembic commands ###
