"""empty message

Revision ID: 20210306_212825
Revises: 20210306_151508
Create Date: 2021-03-06 21:28:25.744854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20210306_212825'
down_revision = '20210306_151508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('margin', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_virtual_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trade_account_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('allocated_margin', sa.DECIMAL(), nullable=False),
    sa.Column('allocation_rate', sa.DECIMAL(), nullable=False),
    sa.Column('ask_limit_rate', sa.DECIMAL(), nullable=True),
    sa.Column('ask_loss_rate', sa.DECIMAL(), nullable=True),
    sa.Column('bid_limit_rate', sa.DECIMAL(), nullable=True),
    sa.Column('bid_loss_rate', sa.DECIMAL(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trade_account_id'], ['trade_account.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_account_id', 'name')
    )
    op.drop_table('trade_acount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_acount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('margin', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trade_acount_pkey')
    )
    op.drop_table('trade_virtual_account')
    op.drop_table('trade_account')
    # ### end Alembic commands ###
