"""empty message

Revision ID: 20210212_004222
Revises: 20210212_004114
Create Date: 2021-02-12 00:42:23.142354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210212_004222"
down_revision = "20210212_004114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tradeorder", "broker", existing_type=sa.VARCHAR(length=1024), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tradeorder", "broker", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    # ### end Alembic commands ###
