"""empty message

Revision ID: 20210211_223817
Revises: 20210208_182036
Create Date: 2021-02-11 22:38:17.905254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210211_223817'
down_revision = '20210208_182036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradeorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('order_at', sa.DateTime(), nullable=True, comment='apiが注文を受け付けた日付'),
    sa.Column('order_id', sa.String(length=255), nullable=True, comment='apiから発行される外部id'),
    sa.Column('bid_or_ask', sa.String(length=255), nullable=True, comment='apiから発行される外部id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, '__crypto_pairs', ['symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, '__crypto_pairs', type_='unique')
    op.drop_table('tradeorder')
    # ### end Alembic commands ###
