"""empty message

Revision ID: 20210326_194157
Revises: 20210326_001319
Create Date: 2021-03-26 19:41:57.595011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210326_194157'
down_revision = '20210326_001319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__crypto_ohlc_daily', sa.Column('t_sma_rate', sa.DECIMAL(), nullable=True))
    op.alter_column('__crypto_ohlc_daily', 'wb_cs_rate',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_comment='white black candle stick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('__crypto_ohlc_daily', 'wb_cs_rate',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_comment='white black candle stick')
    op.drop_column('__crypto_ohlc_daily', 't_sma_rate')
    # ### end Alembic commands ###
