"""empty message

Revision ID: 20210324_213326
Revises: 20210324_211603
Create Date: 2021-03-24 21:33:26.276948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210324_213326'
down_revision = '20210324_211603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_bots', 'product_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('trade_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('trade_profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('trade_bots', 'product_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
