"""empty message

Revision ID: 20210324_225102
Revises: 20210324_213326
Create Date: 2021-03-24 22:51:03.020893

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20210324_225102"
down_revision = "20210324_213326"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_logs",
        sa.Column(
            "fact_profit_rate", sa.DECIMAL(), nullable=True, comment="数量と手数料を含んだ実際の損益率"
        ),
    )
    op.execute("UPDATE trade_logs set fact_profit_rate = 1")
    op.alter_column(
        "trade_logs",
        sa.Column(
            "fact_profit_rate", sa.DECIMAL(), nullable=False, comment="数量と手数料を含んだ実際の損益率"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_logs", "fact_profit_rate")
    # ### end Alembic commands ###
