"""empty message

Revision ID: 20210317_233807
Revises: 20210317_233703
Create Date: 2021-03-17 23:38:07.486793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210317_233807'
down_revision = '20210317_233703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_bots', 'broker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_bots', sa.Column('broker', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
