"""empty message

Revision ID: 20210312_123136
Revises: 20210310_183119
Create Date: 2021-03-12 12:31:36.548172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20210312_123136'
down_revision = '20210310_183119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_order', sa.Column('is_entry', sa.BOOLEAN(), nullable=False))
    op.alter_column('trade_order', 'contract_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='約定日時。Noneなら約定時に現在日時が入力される。バックテストのため、任意の日付を入力可能',
               existing_nullable=True)
    op.drop_column('trade_order', 'profit_loss')
    op.add_column('trade_virtual_account', sa.Column('latest_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trade_virtual_account', 'trade_order', ['latest_order_id'], ['id'])
    op.drop_column('trade_virtual_account', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_virtual_account', sa.Column('position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trade_virtual_account', type_='foreignkey')
    op.drop_column('trade_virtual_account', 'latest_order_id')
    op.add_column('trade_order', sa.Column('profit_loss', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.alter_column('trade_order', 'contract_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='約定日時。Noneなら約定時に現在日時が入力される。バックテストのため、任意の日付を入力可能',
               existing_nullable=True)
    op.drop_column('trade_order', 'is_entry')
    # ### end Alembic commands ###
