"""empty message

Revision ID: 20210306_151508
Revises: 20210306_150804
Create Date: 2021-03-06 15:15:08.696696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210306_151508"
down_revision = "20210306_150804"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trade_acount", sa.Column("margin", sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_acount", "margin")
    # ### end Alembic commands ###
