"""empty message

Revision ID: 20210326_194521
Revises: 20210326_194157
Create Date: 2021-03-26 19:45:21.903385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20210326_194521"
down_revision = "20210326_194157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "__crypto_ohlc_daily", "t_sma_rate", existing_type=sa.NUMERIC(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "__crypto_ohlc_daily", "t_sma_rate", existing_type=sa.NUMERIC(), nullable=True
    )
    # ### end Alembic commands ###
