"""empty message

Revision ID: 20210318_081336
Revises: 20210318_075330
Create Date: 2021-03-18 08:13:36.346224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210318_081336'
down_revision = '20210318_075330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_bots', sa.Column('close_cancel_finalized', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('entry_cancel_finalized', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_bots', 'entry_cancel_finalized')
    op.drop_column('trade_bots', 'close_cancel_finalized')
    # ### end Alembic commands ###
