"""empty message

Revision ID: 20210321_131305
Revises: 20210320_105628
Create Date: 2021-03-21 13:13:06.089147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20210321_131305'
down_revision = '20210320_105628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_bots', sa.Column('close_cancel_order_accepted', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('close_cancel_order_finalized', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('close_order_accepted', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('entry_cancel_order_accepted', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('entry_cancel_order_finalized', sa.JSON(), nullable=True))
    op.add_column('trade_bots', sa.Column('entry_order_accepted', sa.JSON(), nullable=True))
    op.drop_column('trade_bots', 'close_cancel_finalized')
    op.drop_column('trade_bots', 'entry_cancel_finalized')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_bots', sa.Column('entry_cancel_finalized', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trade_bots', sa.Column('close_cancel_finalized', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('trade_bots', 'entry_order_accepted')
    op.drop_column('trade_bots', 'entry_cancel_order_finalized')
    op.drop_column('trade_bots', 'entry_cancel_order_accepted')
    op.drop_column('trade_bots', 'close_order_accepted')
    op.drop_column('trade_bots', 'close_cancel_order_finalized')
    op.drop_column('trade_bots', 'close_cancel_order_accepted')
    # ### end Alembic commands ###
